#!/bin/bash
# Quick setup script for Claude Code Multi-Agent System

echo "🚀 Claude Code Multi-Agent System Setup Complete!"
echo ""
echo "Directory structure created:"
echo "  .claude/"
echo "  ├── agents/         (7 specialized agents)"
echo "  ├── commands/       (9 workflow commands)"
echo "  ├── hooks/          (3 automation hooks)"
echo "  ├── templates/      (2 document templates)"
echo "  ├── specs/          (for feature specifications)"
echo "  └── scripts/        (utility scripts)"
echo ""
echo "✅ All agents have been saved:"
echo "  - product-manager"
echo "  - business-analyst"
echo "  - uiux-designer"
echo "  - architect"
echo "  - developer"
echo "  - qa-engineer"
echo "  - code-reviewer"
echo ""
echo "📚 Documentation:"
echo "  - CLAUDE.md - Main documentation"
echo "  - CONVERSATION_SUMMARY.md - Full conversation summary"
echo ""
echo "🎯 Quick Start:"
echo "  1. cd $(pwd)"
echo "  2. claude"
echo "  3. /project-init \"Your project description\""
echo ""
echo "💡 To see all available agents: /agents"
echo "💡 To see all commands: ls .claude/commands/"